# Generated by Django 4.2.13 on 2026-04-15 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='AWB номер')),
                ('description', models.TextField(blank=True, verbose_name='Описание груза (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание груза (RU)')),
                ('entry_type', models.CharField(blank=True, choices=[('CRST', 'CRST — Courier Road Standard'), ('CB2C', 'CB2C — Courier B2C'), ('CSAD', 'CSAD — Courier SAD'), ('ARST', 'ARST — Air Standard'), ('ASAD', 'ASAD — Air SAD'), ('ADIP', 'ADIP — Air Diplomatic'), ('AB2C', 'AB2C — Air B2C'), ('ARTO', 'ARTO — Air RTO'), ('NTRA', 'NTRA — Non-Transit Air'), ('ATRA', 'ATRA — Air Transit'), ('RTRA', 'RTRA — Road Transit'), ('NPAV', 'NPAV — Non-Pav'), ('C3BR', 'C3BR — Courier 3rd Party Broker'), ('A3BR', 'A3BR — Air 3rd Party Broker'), ('R3BR', 'R3BR — Road 3rd Party Broker'), ('CRTO', 'CRTO — Courier RTO')], max_length=10, verbose_name='Тип записи')),
                ('shp_type', models.CharField(blank=True, choices=[('IMPEX', 'IMPEX — Импорт/Экспорт'), ('B2C', 'B2C — Бизнес для потребителя'), ('B2B', 'B2B — Бизнес для бизнеса'), ('DIP', 'DIP — Дипломатический')], max_length=10, verbose_name='Тип отправителя')),
                ('cpc_code', models.CharField(blank=True, choices=[('BILL_WT', 'BILL WT — Оплата по весу'), ('CED', 'CED — Таможенная декларация'), ('DOCS', 'DOCS — Документы'), ('DRT', 'DRT — Прямой маршрут'), ('FITO', 'FITO — Фитосанитарный'), ('FRG_SHP', 'FRG SHP — Фрахт'), ('PRIVAT', 'PRIVAT — Личный груз'), ('RAPID', 'RAPID — Срочная доставка'), ('STP_CUST', 'STP CUST — Остановлен таможней'), ('SVOLOW0', 'SVOLOW0'), ('SVOLOW1', 'SVOLOW1'), ('SVOLOW2', 'SVOLOW2'), ('SVOLOW3', 'SVOLOW3'), ('SVOLOW4', 'SVOLOW4'), ('SVOLOW5', 'SVOLOW5')], max_length=20, verbose_name='CPC код')),
                ('status', models.CharField(choices=[('EXM1', 'EXM1 — Таможенный осмотр 1'), ('EXM2', 'EXM2 — Таможенный осмотр 2'), ('EXM3', 'EXM3 — Таможенный осмотр 3'), ('EXM4', 'EXM4 — Таможенный осмотр 4'), ('DIP', 'DIP  — Дипломатический груз'), ('MPWI', 'MPWI — Недостача мест'), ('BTFR', 'BTFR — Передача брокеру'), ('NCI', 'NCI  — Нет коммерческого инвойса'), ('CNPK', 'CNPK — Консолидированная посылка'), ('CIDM', 'CIDM — Проверка документов'), ('CIDI', 'CIDI — Проверка ID'), ('CVAL', 'CVAL — Проверка стоимости'), ('VALU', 'VALU — Оценка'), ('DUTY', 'DUTY — Расчёт пошлины'), ('ILRQ', 'ILRQ — Запрос лицензии'), ('XMPT', 'XMPT — Освобождение от пошлины'), ('INST', 'INST — Инструкции'), ('SHPK', 'SHPK — Доставка упакована'), ('HOLD', 'HOLD — Удержан декларантом'), ('EXAM', 'EXAM — Таможенный досмотр'), ('HLDP', 'HLDP — Удержан таможней'), ('RLSE', 'RLSE — Выпущен'), ('REJ', 'REJ  — Отклонён'), ('BRKR', 'BRKR — Передан брокеру'), ('PMIS', 'PMIS — Частичная недостача'), ('RTO', 'RTO  — Возврат отправителю')], db_index=True, default='CNPK', max_length=10, verbose_name='Статус')),
                ('queue', models.CharField(choices=[('CS', 'CS  — Clearance Support'), ('BR', 'BR  — Broker Review'), ('PC3', 'PC3 — Pending Closure 3rd Party'), ('PC', 'PC  — Pending Clearance'), ('ER', 'ER  — Entry Released'), ('REJ', 'REJ — Rejected Imports'), ('TRASH', 'TRASH — Корзина'), ('FLT', 'FLT — Flight Reconciliation')], db_index=True, default='CS', max_length=10, verbose_name='Очередь')),
                ('last_status_change', models.DateTimeField(blank=True, null=True, verbose_name='Последнее изменение статуса')),
                ('flight_number', models.CharField(blank=True, max_length=20, verbose_name='Номер рейса')),
                ('flight_date', models.DateField(blank=True, null=True, verbose_name='Дата рейса')),
                ('departure_iata', models.CharField(blank=True, max_length=3, verbose_name='IATA отправления')),
                ('arrival_iata', models.CharField(blank=True, max_length=3, verbose_name='IATA прибытия')),
                ('movement_number', models.CharField(blank=True, max_length=50, verbose_name='Номер муверского')),
                ('transportation_mode', models.IntegerField(choices=[(1, '1 — Морской'), (2, '2 — Железнодорожный'), (3, '3 — Автомобильный'), (4, '4 — Авиа'), (5, '5 — Почтовый'), (7, '7 — Трубопроводный')], default=4, verbose_name='Вид транспорта')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес (кг)')),
                ('pieces_declared', models.IntegerField(default=0, verbose_name='Мест заявлено')),
                ('pieces_arrived', models.IntegerField(default=0, verbose_name='Мест прибыло')),
                ('pieces_missing', models.IntegerField(default=0, verbose_name='Мест недостача')),
                ('invoice_currency', models.CharField(choices=[('USD', 'USD — Доллар США'), ('EUR', 'EUR — Евро'), ('CNY', 'CNY — Китайский юань'), ('GBP', 'GBP — Фунт стерлингов'), ('RUB', 'RUB — Российский рубль')], default='USD', max_length=3, verbose_name='Валюта инвойса')),
                ('invoice_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Стоимость по инвойсу')),
                ('customs_value_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Таможенная стоимость (RUB)')),
                ('duty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма пошлины')),
                ('warehouse_name', models.CharField(blank=True, max_length=200, verbose_name='Название склада')),
                ('warehouse_license', models.CharField(blank=True, max_length=50, verbose_name='№ лицензии склада')),
                ('bond_location', models.CharField(blank=True, max_length=100, verbose_name='Ячейка хранения')),
                ('scan_into_bond', models.DateTimeField(blank=True, null=True, verbose_name='Въезд на склад')),
                ('scan_out_of_bond', models.DateTimeField(blank=True, null=True, verbose_name='Выезд со склада')),
                ('aca_location', models.CharField(blank=True, max_length=100, verbose_name='ACA локация')),
                ('customs_declaration_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Номер ТД')),
                ('customs_status', models.CharField(blank=True, max_length=100, verbose_name='Таможенный статус')),
                ('entry_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата подачи декларации')),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('is_transit', models.BooleanField(default=False, verbose_name='Транзитный груз')),
                ('bonded_dest', models.CharField(blank=True, max_length=100, verbose_name='Таможенный пункт назначения')),
                ('bonded_transit', models.CharField(blank=True, max_length=100, verbose_name='Таможенный транзит')),
                ('rto_reason', models.CharField(blank=True, choices=[('REFUSAL_DOX', 'Отказ — документы'), ('NO_DOX', 'Нет документов'), ('PRIVATE', 'Частный получатель'), ('UNSERVICED', 'Необслуживаемый регион'), ('UNDERVALUE', 'Занижение стоимости'), ('PROHIBITED', 'Запрещённый товар'), ('NCI', 'Нет коммерческого инвойса'), ('RTO_REQUEST', 'Запрос возврата'), ('DDP', 'DDP — доставка с оплатой пошлин'), ('PAYMENT_REFUSAL', 'Отказ от оплаты'), ('MISCODE', 'Неверный код товара')], max_length=30, verbose_name='Причина RTO')),
                ('declarant', models.CharField(blank=True, max_length=100, verbose_name='Декларант (логин)')),
                ('declarant_notes', models.TextField(blank=True, verbose_name='Примечания декларанта')),
                ('payer_account', models.CharField(blank=True, max_length=50, verbose_name='Счёт плательщика')),
                ('shipper_account', models.CharField(blank=True, max_length=50, verbose_name='Счёт отправителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cargos', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название склада')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='№ лицензии СВХ')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('iata_code', models.CharField(blank=True, max_length=3, verbose_name='IATA код')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('max_capacity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Макс. ёмкость (кг)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Склад СВХ',
                'verbose_name_plural': 'Склады СВХ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=10, verbose_name='Прежний статус')),
                ('new_status', models.CharField(max_length=10, verbose_name='Новый статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время изменения')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='cargo.cargo', verbose_name='Груз')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, verbose_name='Номер рейса')),
                ('flight_date', models.DateField(verbose_name='Дата рейса')),
                ('airline', models.CharField(blank=True, max_length=100, verbose_name='Авиакомпания')),
                ('departure_iata', models.CharField(max_length=3, verbose_name='IATA отправления')),
                ('arrival_iata', models.CharField(max_length=3, verbose_name='IATA прибытия')),
                ('scheduled_departure', models.DateTimeField(blank=True, null=True, verbose_name='Плановый вылет')),
                ('scheduled_arrival', models.DateTimeField(blank=True, null=True, verbose_name='Плановое прибытие')),
                ('actual_departure', models.DateTimeField(blank=True, null=True, verbose_name='Фактический вылет')),
                ('actual_arrival', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое прибытие')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Статус рейса')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'ordering': ['-flight_date', 'flight_number'],
                'unique_together': {('flight_number', 'flight_date')},
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='cargo.warehouse', verbose_name='Склад СВХ'),
        ),
    ]
