# Generated by Django 4.2.13 on 2026-04-15 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='queue',
            field=models.CharField(choices=[('CS', 'CS  — Поддержка оформления'), ('BR', 'BR  — Проверка брокером'), ('PC3', 'PC3 — Ожидание закрытия (3я сторона)'), ('PC', 'PC  — Ожидание оформления'), ('ER', 'ER  — Груз выпущен'), ('REJ', 'REJ — Отклонённые грузы'), ('TRASH', 'TRASH — Корзина'), ('FLT', 'FLT — Сверка рейса')], db_index=True, default='CS', max_length=10, verbose_name='Очередь'),
        ),
        migrations.CreateModel(
            name='CargoAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('declarant', 'Декларант'), ('broker', 'Брокер'), ('manager', 'Менеджер'), ('supervisor', 'Супервайзер'), ('inspector', 'Инспектор')], default='declarant', max_length=20, verbose_name='Роль')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата назначения')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cargos', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cargo.cargo', verbose_name='Груз')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Назначение сотрудника',
                'verbose_name_plural': 'Назначения сотрудников',
                'ordering': ['-assigned_at'],
                'unique_together': {('cargo', 'user', 'role')},
            },
        ),
    ]
