# Generated by Django 4.2.13 on 2026-04-15 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo', '0002_alter_cargo_queue_cargoassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseWaybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hawb_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Номер HAWB')),
                ('description', models.TextField(blank=True, verbose_name='Описание груза')),
                ('consignee_name', models.CharField(blank=True, max_length=200, verbose_name='Получатель')),
                ('consignee_address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('consignee_city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('consignee_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('consignee_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('consignee_inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН получателя')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес (кг)')),
                ('pieces_declared', models.IntegerField(default=1, verbose_name='Мест заявлено')),
                ('pieces_arrived', models.IntegerField(default=0, verbose_name='Мест прибыло')),
                ('invoice_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Стоимость')),
                ('invoice_currency', models.CharField(choices=[('USD', 'USD — Доллар США'), ('EUR', 'EUR — Евро'), ('CNY', 'CNY — Китайский юань'), ('GBP', 'GBP — Фунт стерлингов'), ('RUB', 'RUB — Российский рубль')], default='USD', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('EXM1', 'EXM1 — Таможенный осмотр 1'), ('EXM2', 'EXM2 — Таможенный осмотр 2'), ('EXM3', 'EXM3 — Таможенный осмотр 3'), ('EXM4', 'EXM4 — Таможенный осмотр 4'), ('DIP', 'DIP  — Дипломатический груз'), ('MPWI', 'MPWI — Недостача мест'), ('BTFR', 'BTFR — Передача брокеру'), ('NCI', 'NCI  — Нет коммерческого инвойса'), ('CNPK', 'CNPK — Консолидированная посылка'), ('CIDM', 'CIDM — Проверка документов'), ('CIDI', 'CIDI — Проверка ID'), ('CVAL', 'CVAL — Проверка стоимости'), ('VALU', 'VALU — Оценка'), ('DUTY', 'DUTY — Расчёт пошлины'), ('ILRQ', 'ILRQ — Запрос лицензии'), ('XMPT', 'XMPT — Освобождение от пошлины'), ('INST', 'INST — Инструкции'), ('SHPK', 'SHPK — Доставка упакована'), ('HOLD', 'HOLD — Удержан декларантом'), ('EXAM', 'EXAM — Таможенный досмотр'), ('HLDP', 'HLDP — Удержан таможней'), ('RLSE', 'RLSE — Выпущен'), ('REJ', 'REJ  — Отклонён'), ('BRKR', 'BRKR — Передан брокеру'), ('PMIS', 'PMIS — Частичная недостача'), ('RTO', 'RTO  — Возврат отправителю')], db_index=True, default='CNPK', max_length=10, verbose_name='Статус')),
                ('last_status_change', models.DateTimeField(blank=True, null=True, verbose_name='Изменение статуса')),
                ('customs_declaration_number', models.CharField(blank=True, max_length=50, verbose_name='Номер ТД')),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hawb_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('mawb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hawbs', to='cargo.cargo', verbose_name='Основная накладная (MAWB)')),
            ],
            options={
                'verbose_name': 'Индивидуальная накладная (HAWB)',
                'verbose_name_plural': 'Индивидуальные накладные (HAWB)',
                'ordering': ['hawb_number'],
            },
        ),
    ]
