# Generated by Django 4.2.13 on 2026-04-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_housewaybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='housewaybill',
            name='doc_invoice',
            field=models.BooleanField(default=False, verbose_name='Инвойс'),
        ),
        migrations.AddField(
            model_name='housewaybill',
            name='doc_packing_list',
            field=models.BooleanField(default=False, verbose_name='Упаковочный лист'),
        ),
        migrations.AddField(
            model_name='housewaybill',
            name='doc_permit',
            field=models.BooleanField(default=False, verbose_name='Разрешительные документы'),
        ),
        migrations.AddField(
            model_name='housewaybill',
            name='doc_tech_desc',
            field=models.BooleanField(default=False, verbose_name='Техническое описание'),
        ),
    ]
