# Generated by Django 4.2.13 on 2026-04-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_housewaybill_doc_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housewaybill',
            name='cargo_type',
            field=models.CharField(choices=[('B2C', 'B2C — Бизнес для потребителя'), ('B2B', 'B2B — Бизнес для бизнеса'), ('C2C', 'C2C — Частное лицо')], default='B2C', max_length=5, verbose_name='Тип груза'),
        ),
        migrations.AddField(
            model_name='housewaybill',
            name='scan_into_bond',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата размещения на СВХ (ДО1)'),
        ),
        migrations.AddField(
            model_name='housewaybill',
            name='shipment_type',
            field=models.CharField(choices=[('IMPORT', 'Импорт'), ('EXPORT', 'Экспорт')], default='IMPORT', max_length=10, verbose_name='Тип отправки'),
        ),
    ]
