# Generated by Django 4.2.13 on 2026-04-15 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0005_housewaybill_cargo_type_housewaybill_scan_into_bond_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housewaybill',
            name='docs_required',
            field=models.IntegerField(default=4, help_text='Настраивается вручную — сколько документов нужно для подачи', verbose_name='Требуется документов'),
        ),
        migrations.CreateModel(
            name='HAWBGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование товара')),
                ('tnved_code', models.CharField(blank=True, max_length=20, verbose_name='Код ТН ВЭД')),
                ('brand', models.CharField(blank=True, max_length=200, verbose_name='Торговая марка')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Изготовитель')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='Модель')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='Количество')),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='Единица измерения')),
                ('weight_net', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Вес нетто (кг)')),
                ('weight_gross', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Вес брутто (кг)')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Цена за единицу')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Общая стоимость')),
                ('currency', models.CharField(choices=[('USD', 'USD — Доллар США'), ('EUR', 'EUR — Евро'), ('CNY', 'CNY — Китайский юань'), ('GBP', 'GBP — Фунт стерлингов'), ('RUB', 'RUB — Российский рубль')], default='USD', max_length=3, verbose_name='Валюта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hawb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='cargo.housewaybill', verbose_name='Накладная')),
            ],
            options={
                'verbose_name': 'Товарная позиция',
                'verbose_name_plural': 'Товарные позиции',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HAWBDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('invoice', 'Инвойс'), ('packing_list', 'Упаковочный лист'), ('permit', 'Разрешительный документ'), ('tech_desc', 'Техническое описание'), ('certificate', 'Сертификат'), ('declaration', 'Декларация'), ('other', 'Иное')], default='other', max_length=20, verbose_name='Тип документа')),
                ('name', models.CharField(max_length=300, verbose_name='Название документа')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер документа')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('is_received', models.BooleanField(default=False, verbose_name='Получен')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hawb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cargo.housewaybill', verbose_name='Накладная')),
            ],
            options={
                'verbose_name': 'Документ HAWB',
                'verbose_name_plural': 'Документы HAWB',
                'ordering': ['doc_type', 'name'],
            },
        ),
    ]
