# Generated by Django 4.2.13 on 2026-04-15 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0006_housewaybill_docs_required_hawbgood_hawbdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housewaybill',
            name='mawb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hawbs', to='cargo.cargo', verbose_name='Основная накладная (MAWB)'),
        ),
    ]
