# Generated by Django 4.2.13 on 2026-04-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_hawb_new_statuses'),
        ('cargo', '0007_alter_housewaybill_mawb'),
    ]

    operations = [
    ]
