# Generated by Django 4.2.13 on 2026-04-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_cargo_stage'),
        ('cargo', '0008_merge_20260416_1137'),
    ]

    operations = [
    ]
