# Generated by Django 4.2.13 on 2026-04-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0009_merge_0003_cargo_stage_0008_merge_20260416_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='departure_date',
            field=models.DateField(blank=True, help_text='Недоступно на этапах Формирование / Сформирована', null=True, verbose_name='Дата вылета'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='flight_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата прилёта'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='status',
            field=models.CharField(choices=[], db_index=True, default='CNPK', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='housewaybill',
            name='status',
            field=models.CharField(blank=True, choices=[], db_index=True, default='CNPK', max_length=10, verbose_name='Статус (устар.)'),
        ),
    ]
