# Generated by Django 4.2.13 on 2026-04-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0010_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='transportation_mode',
            field=models.IntegerField(choices=[(1, 'Морской'), (2, 'Железнодорожный'), (3, 'Автомобильный'), (4, 'Авиа'), (5, 'Почтовый')], default=4, verbose_name='Вид транспорта'),
        ),
        migrations.AlterField(
            model_name='housewaybill',
            name='cargo_type',
            field=models.CharField(choices=[('B2C', 'B2C — Бизнес для потребителя'), ('B2B', 'B2B — Бизнес для бизнеса'), ('C2C', 'C2C — Частное лицо'), ('DOC', 'Документация')], default='B2C', max_length=5, verbose_name='Тип груза'),
        ),
    ]
