# Generated by Django 4.2.13 on 2026-04-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0015_hawbgood_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='hawbgood',
            name='cargo_type',
            field=models.CharField(blank=True, choices=[('B2C', 'B2C — Бизнес для потребителя'), ('B2B', 'B2B — Бизнес для бизнеса'), ('C2C', 'C2C — Частное лицо'), ('DOC', 'Документация')], default='', max_length=5, verbose_name='Тип груза'),
        ),
    ]
