# Generated by Django 4.2.13 on 2026-04-20 12:28

from django.db import migrations


def backfill_cargo_type(apps, schema_editor):
    """Заполняем cargo_type для существующих товаров из родительского HAWB."""
    HAWBGood = apps.get_model('cargo', 'HAWBGood')
    goods = HAWBGood.objects.filter(cargo_type='').select_related('hawb')
    for good in goods:
        good.cargo_type = good.hawb.cargo_type or 'B2C'
        good.save(update_fields=['cargo_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0016_hawbgood_cargo_type'),
    ]

    operations = [
        migrations.RunPython(backfill_cargo_type, migrations.RunPython.noop),
    ]
