# Generated by Django 4.2.13 on 2026-04-21 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo', '0017_hawbgood_cargo_type_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('stat', 'Метрика'), ('kanban', 'Канбан'), ('table', 'Таблица'), ('chart_stage', 'График: этапы'), ('chart_warehouse', 'График: склады')], default='stat', max_length=30, verbose_name='Тип')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('filter_query', models.TextField(blank=True, default='', verbose_name='Фильтр (CQL)')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Конфигурация')),
                ('pos_x', models.IntegerField(default=0, verbose_name='Позиция X')),
                ('pos_y', models.IntegerField(default=9999, verbose_name='Позиция Y')),
                ('width', models.IntegerField(default=3, verbose_name='Ширина (колонки)')),
                ('height', models.IntegerField(default=2, verbose_name='Высота (строки)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Виджет дашборда',
                'verbose_name_plural': 'Виджеты дашборда',
                'ordering': ['pos_y', 'pos_x'],
            },
        ),
    ]
