# Generated by Django 4.2.13 on 2026-04-21 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo', '0018_dashboardwidget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бизнес-процесс',
                'verbose_name_plural': 'Бизнес-процессы',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('step_type', models.CharField(choices=[('stage', 'Этап партии'), ('action', 'Действие'), ('check', 'Проверка/условие'), ('notify', 'Уведомление')], default='stage', max_length=20, verbose_name='Тип')),
                ('stage', models.CharField(blank=True, choices=[('DRAFT', 'Формирование партии'), ('FORMED', 'Партия сформирована'), ('DISPATCHED', 'Партия отправлена в страну назначения'), ('ARRIVED', 'Партия прибыла в страну назначения'), ('CUSTOMS', 'Таможенное оформление в стране назначения'), ('RELEASED', 'Полный выпуск')], default='', max_length=20, verbose_name='Привязка к этапу')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Конфигурация')),
                ('pos_x', models.IntegerField(default=0, verbose_name='X на холсте')),
                ('pos_y', models.IntegerField(default=0, verbose_name='Y на холсте')),
                ('color', models.CharField(default='#3b82f6', max_length=20, verbose_name='Цвет')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cargo.workflow')),
            ],
            options={
                'verbose_name': 'Шаг процесса',
                'verbose_name_plural': 'Шаги процесса',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=200, verbose_name='Подпись')),
                ('condition', models.TextField(blank=True, default='', verbose_name='Условие (CQL)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('from_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_out', to='cargo.workflowstep')),
                ('to_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_in', to='cargo.workflowstep')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='cargo.workflow')),
            ],
            options={
                'verbose_name': 'Переход',
                'verbose_name_plural': 'Переходы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('action_type', models.CharField(choices=[('assign_user', 'Назначить пользователя'), ('set_field', 'Установить поле'), ('send_notify', 'Отправить уведомление'), ('change_stage', 'Перевести этап'), ('webhook', 'Вызвать webhook')], max_length=20, verbose_name='Тип действия')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='cargo.workflowtransition')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='cargo.workflow')),
            ],
            options={
                'verbose_name': 'Правило автоматизации',
                'verbose_name_plural': 'Правила автоматизации',
                'ordering': ['order'],
            },
        ),
    ]
