# Generated by Django 4.2.13 on 2026-04-21 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo', '0019_workflow_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('cargo', 'Партия'), ('hawb', 'Накладная')], max_length=10, verbose_name='Тип сущности')),
                ('entity_id', models.IntegerField(db_index=True, verbose_name='ID сущности')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Запущен')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
            ],
            options={
                'verbose_name': 'Экземпляр бизнес-процесса',
                'verbose_name_plural': 'Экземпляры бизнес-процессов',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='workflow',
            name='auto_start',
            field=models.BooleanField(default=True, verbose_name='Авто-старт при создании'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='entity_type',
            field=models.CharField(choices=[('cargo', 'Партия (MAWB)'), ('hawb', 'Накладная (HAWB)')], default='cargo', max_length=10, verbose_name='Тип сущности'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='trigger_conditions',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"cargo_type":"B2B","shipment_type":"IMPORT"}', verbose_name='Условия запуска'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='hawb_customs_status',
            field=models.CharField(blank=True, choices=[('BROKER_CHECK', 'Проверка брокером'), ('READY_TO_FILE', 'Готов к подаче'), ('FILED', 'Подан'), ('EXAMINATION', 'Досмотр'), ('HOLD', 'Удержан'), ('RELEASED', 'Выпущен'), ('REJECTED', 'Отказ')], default='', max_length=20, verbose_name='Там. статус накладной'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='hawb_logistics_status',
            field=models.CharField(blank=True, choices=[('CREATED', 'Создан'), ('TO_ORIGIN_WH', 'В пути на склад отправки'), ('AT_ORIGIN_WH', 'Принят на склад отправки'), ('CONSOLIDATED', 'В консоли'), ('READY_TO_SHIP', 'Готов к отправке'), ('EXPORT_CUSTOMS', 'Экспортная таможня'), ('IN_TRANSIT_EXP', 'В пути в страну назначения'), ('ARRIVED_DEST', 'Прибыл в страну назначения'), ('AT_SVH', 'На СВХ'), ('IMPORT_CUSTOMS', 'Импортная таможня'), ('READY_DELIVERY', 'Готов к выдаче'), ('TO_SORT_CENTER', 'На сортировку'), ('AT_SORT_CENTER', 'На сортировочном центре'), ('READY_TO_DEST', 'Готов к доставке'), ('IN_TRANSIT_DEST', 'В пути к получателю'), ('ARRIVED_FINAL', 'Прибыл к получателю'), ('DELIVERED', 'Вручено'), ('RETURNED', 'Возврат'), ('LOST', 'Утеря')], default='', max_length=20, verbose_name='Лог. статус накладной'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='stage',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Формирование партии'), ('FORMED', 'Партия сформирована'), ('DISPATCHED', 'Партия отправлена в страну назначения'), ('ARRIVED', 'Партия прибыла в страну назначения'), ('CUSTOMS', 'Таможенное оформление в стране назначения'), ('RELEASED', 'Полный выпуск')], default='', max_length=20, verbose_name='Привязка к этапу партии'),
        ),
        migrations.CreateModel(
            name='WorkflowInstanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('note', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('automation_log', models.JSONField(default=list, help_text='Список выполненных автоматизаций и их результатов', verbose_name='Лог автоматизаций')),
                ('from_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_from', to='cargo.workflowstep', verbose_name='Откуда')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cargo.workflowinstance', verbose_name='Экземпляр')),
                ('to_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_to', to='cargo.workflowstep', verbose_name='Куда')),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargo.workflowtransition', verbose_name='Переход')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Событие бизнес-процесса',
                'verbose_name_plural': 'События бизнес-процессов',
                'ordering': ['triggered_at'],
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_instances', to='cargo.workflowstep', verbose_name='Текущий шаг'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_workflow_instances', to=settings.AUTH_USER_MODEL, verbose_name='Запущен пользователем'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='cargo.workflow', verbose_name='Бизнес-процесс'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowinstance',
            unique_together={('workflow', 'entity_type', 'entity_id')},
        ),
    ]
