# Generated by Django 4.2.13 on 2026-04-24 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo', '0022_dashboardwidget_pivot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Название')),
                ('color', models.CharField(default='#6c757d', help_text='HEX-код цвета, например #ff5722', max_length=7, verbose_name='Цвет (hex)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_labels', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='cargos', to='cargo.label', verbose_name='Метки'),
        ),
        migrations.AddField(
            model_name='housewaybill',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='hawbs', to='cargo.label', verbose_name='Метки'),
        ),
    ]
