# Generated by Django 4.2.13 on 2026-04-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0023_add_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(choices=[('stat', 'Метрика'), ('kanban', 'Канбан'), ('table', 'Таблица'), ('chart_stage', 'График: этапы'), ('chart_warehouse', 'График: склады'), ('chart_pie', 'Круговая диаграмма'), ('forecast_arrivals', 'Прогноз прилётов'), ('pivot', 'Сводная таблица')], default='stat', max_length=30, verbose_name='Тип'),
        ),
    ]
