# Generated by Django 4.2.13 on 2026-04-24 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0024_alter_dashboardwidget_widget_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='sla_hours_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Если задано — перекрывает глобальный SLAPolicy для сущностей на этом шаге', max_digits=7, null=True, verbose_name='SLA (часы), override'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='action_type',
            field=models.CharField(choices=[('assign_user', 'Назначить пользователя'), ('set_field', 'Установить поле'), ('send_notify', 'Отправить уведомление'), ('change_stage', 'Перевести этап'), ('webhook', 'Вызвать webhook'), ('sla_breach_notify', 'Уведомить о просрочке SLA')], max_length=20, verbose_name='Тип действия'),
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Название')),
                ('entity_type', models.CharField(choices=[('cargo', 'Партия'), ('hawb', 'Накладная')], max_length=10, verbose_name='Сущность')),
                ('status_field', models.CharField(choices=[('stage', 'Этап партии'), ('logistics_status', 'Лог. статус накладной'), ('customs_status', 'Там. статус накладной')], max_length=20, verbose_name='Поле статуса')),
                ('status_value', models.CharField(max_length=30, verbose_name='Значение статуса')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Норматив (часы)')),
                ('warning_threshold_pct', models.IntegerField(default=75, help_text='При каком проценте израсходованного времени полоса становится жёлтой', verbose_name='Порог жёлтой зоны, %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SLA-норматив',
                'verbose_name_plural': 'SLA-нормативы',
                'ordering': ['entity_type', 'status_field', 'status_value'],
                'unique_together': {('entity_type', 'status_field', 'status_value')},
            },
        ),
        migrations.CreateModel(
            name='SLABreachEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=10, verbose_name='Тип сущности')),
                ('entity_id', models.IntegerField(db_index=True, verbose_name='ID сущности')),
                ('breached_at', models.DateTimeField(verbose_name='Момент просрочки')),
                ('notified', models.BooleanField(default=False, verbose_name='Уведомление отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaches', to='cargo.slapolicy')),
                ('workflow_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_breaches', to='cargo.workflowinstance')),
            ],
            options={
                'verbose_name': 'Событие просрочки SLA',
                'verbose_name_plural': 'События просрочки SLA',
                'ordering': ['-breached_at'],
                'unique_together': {('policy', 'entity_type', 'entity_id', 'breached_at')},
            },
        ),
    ]
