# Generated by Django 4.2.13 on 2026-05-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0025_sla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='entry_type',
        ),
    ]
