# Generated by Django 4.2.13 on 2026-05-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0026_remove_cargo_entry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='pieces_arrived',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='pieces_missing',
        ),
        migrations.RemoveField(
            model_name='housewaybill',
            name='pieces_arrived',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='pieces_declared',
            field=models.IntegerField(default=0, verbose_name='Мест'),
        ),
        migrations.AlterField(
            model_name='housewaybill',
            name='pieces_declared',
            field=models.IntegerField(default=1, verbose_name='Мест'),
        ),
    ]
