# Generated by Django 4.2.13 on 2026-05-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0027_remove_cargo_pieces_arrived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='is_self_clearance',
            field=models.BooleanField(default=False, help_text='Клиент сам выпускает груз; наш брокер не задействован', verbose_name='ТО клиентом'),
        ),
    ]
