# Generated by Django 4.2.13 on 2026-05-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0028_cargo_is_self_clearance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='customs_status',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='declarant',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='declarant_notes',
        ),
    ]
