# Generated by Django 4.2.13 on 2026-05-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0029_remove_cargo_customs_status_remove_cargo_declarant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='aca_location',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='housewaybill',
            name='status',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='last_status_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее изменение этапа'),
        ),
    ]
