# Generated by Django 4.2.13 on 2026-05-02 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo', '0031_workload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingnorm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workloadrebalancelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='WorkScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Начало (включительно)')),
                ('date_to', models.DateField(verbose_name='Окончание (включительно)')),
                ('kind', models.CharField(choices=[('vacation', 'Отпуск'), ('sick', 'Больничный'), ('day_off', 'Отгул'), ('holiday', 'Праздник'), ('other', 'Иное')], default='vacation', max_length=20, verbose_name='Тип')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Исключение из графика',
                'verbose_name_plural': 'Исключения из графика',
                'ordering': ['-date_from'],
                'indexes': [models.Index(fields=['user', 'date_from', 'date_to'], name='cargo_works_user_id_75de16_idx')],
            },
        ),
    ]
