# Generated by Django 4.2.13 on 2026-05-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0032_workload_exceptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название организации')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки организации',
                'verbose_name_plural': 'Настройки организации',
            },
        ),
    ]
