# Generated by Django 4.2.13 on 2026-05-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0033_organization_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30, verbose_name='Расчётный счёт (Р/с)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='bank_bik',
            field=models.CharField(blank=True, max_length=20, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='bank_corr_account',
            field=models.CharField(blank=True, max_length=30, verbose_name='Корреспондентский счёт (К/с)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Банк (филиал)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='manifest_shipper',
            field=models.CharField(blank=True, help_text='Заполняется в столбец «Грузоотправитель» во всех строках манифеста', max_length=200, verbose_name='Грузоотправитель в манифесте'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='ogrn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ОГРН'),
        ),
    ]
