# Generated by Django 4.2.13 on 2026-05-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0034_organization_bank_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='housewaybill',
            name='shipper_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Грузоотправитель'),
        ),
    ]
