# Generated by Django 4.2.13 on 2026-05-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0035_hawb_shipper_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='housewaybill',
            name='shipper_address',
            field=models.TextField(blank=True, verbose_name='Адрес отправителя'),
        ),
        migrations.AddField(
            model_name='housewaybill',
            name='shipper_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город отправителя'),
        ),
        migrations.AddField(
            model_name='housewaybill',
            name='shipper_inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ИНН отправителя'),
        ),
        migrations.AddField(
            model_name='housewaybill',
            name='shipper_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон отправителя'),
        ),
    ]
