# Generated by Django 4.2.13 on 2026-05-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0036_hawb_shipper_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='hawbgood',
            name='product_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка на товар'),
        ),
        migrations.AddField(
            model_name='hawbgood',
            name='quantity_additional',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Кол-во в ДЕИ'),
        ),
        migrations.AddField(
            model_name='hawbgood',
            name='unit_additional',
            field=models.CharField(blank=True, max_length=20, verbose_name='Доп. единица (ДЕИ)'),
        ),
    ]
