# Generated by Django 4.2.13 on 2026-05-11 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo', '0037_hawbgood_product_url_additional_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltaQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('indpost', 'Почтовая накладная'), ('waybill', 'Накладная (ЭД-2)'), ('invoice', 'Инвойс'), ('express', 'Реестр экспресс-грузов'), ('dt', 'Декларация на товары')], db_index=True, max_length=16, verbose_name='Тип документа')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('content', models.BinaryField(verbose_name='XML (байты в исходной кодировке)')),
                ('content_encoding', models.CharField(default='utf-8', max_length=32, verbose_name='Кодировка')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Попыток отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alta_queue_items', to='cargo.cargo', verbose_name='Партия (MAWB)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alta_queue_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто поставил')),
                ('hawb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alta_queue_items', to='cargo.housewaybill', verbose_name='HAWB')),
            ],
            options={
                'verbose_name': 'Документ в очереди на Альту',
                'verbose_name_plural': 'Очередь отправки в Альту',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='cargo_altaq_status_914f8e_idx')],
            },
        ),
    ]
