# Generated by Django 4.2.13 on 2026-05-12 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo', '0038_alta_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='housewaybill',
            name='problem_note',
            field=models.TextField(blank=True, help_text='Описание текущей проблемы по накладной (колонка "Проблема" из Sheets)', verbose_name='Проблема'),
        ),
        migrations.AddField(
            model_name='housewaybill',
            name='tsd_number',
            field=models.CharField(blank=True, help_text='Номер транспортного сопроводительного документа', max_length=64, verbose_name='ТСД'),
        ),
        migrations.AddField(
            model_name='housewaybill',
            name='ved_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ved_managed_hawbs', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер ВЭД'),
        ),
        migrations.AlterField(
            model_name='altaqueueitem',
            name='doc_type',
            field=models.CharField(choices=[('indpost', 'Накладная'), ('waybill', 'Накладная (ЭД-2)'), ('invoice', 'Инвойс'), ('express', 'Реестр экспресс-грузов'), ('dt', 'Декларация на товары')], db_index=True, max_length=16, verbose_name='Тип документа'),
        ),
        migrations.CreateModel(
            name='SheetUserAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200, unique=True, verbose_name='ФИО как в Sheets')),
                ('role_hint', models.CharField(blank=True, choices=[('', '—'), ('ved_manager', 'Менеджер ВЭД'), ('declarant', 'Декларант / ответственный по ТО'), ('broker', 'Брокер'), ('manager', 'Менеджер')], max_length=20, verbose_name='Роль (подсказка)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Алиас пользователя из Sheets',
                'verbose_name_plural': 'Алиасы пользователей из Sheets',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='SheetSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Произвольное имя для отображения в UI', max_length=100, verbose_name='Название')),
                ('kind', models.CharField(choices=[('general', 'Таблица "Общее"'), ('crm', 'Таблица CRM')], db_index=True, max_length=20, verbose_name='Тип источника')),
                ('spreadsheet_id', models.CharField(help_text='ID из URL Google-таблицы', max_length=128, verbose_name='Spreadsheet ID')),
                ('tab_name', models.CharField(max_length=128, verbose_name='Имя вкладки')),
                ('header_row', models.PositiveIntegerField(default=1, help_text='1-based номер строки с заголовками колонок', verbose_name='Номер строки шапки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_imported_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний импорт')),
                ('last_status', models.CharField(blank=True, choices=[('', '—'), ('ok', 'OK'), ('error', 'Ошибка')], max_length=10, verbose_name='Последний статус')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Источник Google Sheets',
                'verbose_name_plural': 'Источники Google Sheets',
                'ordering': ['kind', 'name'],
                'unique_together': {('spreadsheet_id', 'tab_name')},
            },
        ),
        migrations.CreateModel(
            name='SheetImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('status', models.CharField(choices=[('running', 'В процессе'), ('ok', 'Успешно'), ('error', 'Ошибка')], default='running', max_length=10, verbose_name='Статус')),
                ('rows_total', models.PositiveIntegerField(default=0, verbose_name='Всего строк')),
                ('rows_new', models.PositiveIntegerField(default=0, verbose_name='Новых')),
                ('rows_changed', models.PositiveIntegerField(default=0, verbose_name='Изменившихся')),
                ('rows_unchanged', models.PositiveIntegerField(default=0, verbose_name='Без изменений')),
                ('rows_matched', models.PositiveIntegerField(default=0, verbose_name='Сматчены')),
                ('rows_orphan', models.PositiveIntegerField(default=0, verbose_name='Orphan')),
                ('rows_conflict', models.PositiveIntegerField(default=0, verbose_name='Конфликты')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('dry_run', models.BooleanField(default=False, verbose_name='Dry-run')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='cargo.sheetsource')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_import_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогон импорта',
                'verbose_name_plural': 'Прогоны импорта',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedSheetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_index', models.PositiveIntegerField(db_index=True, verbose_name='№ строки в Sheets')),
                ('data', models.JSONField(default=dict, verbose_name='Сырые данные')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='Hash контента')),
                ('hawb_number_raw', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='HAWB (как в Sheets)')),
                ('hawb_number_norm', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='HAWB (нормализованный)')),
                ('inn_raw', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='ИНН (как в Sheets)')),
                ('declaration_number', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='№ ДТ')),
                ('match_status', models.CharField(choices=[('unmatched', 'Не обработано'), ('matched', 'Совпадает с HAWB'), ('orphan', 'Нет соответствия в БД'), ('conflict', 'Несколько кандидатов'), ('ambiguous', 'Нет ключа для матчинга'), ('promoted', 'Промоутнуто в HAWB'), ('ignored', 'Исключено вручную')], db_index=True, default='unmatched', max_length=20, verbose_name='Статус матчинга')),
                ('diff_summary', models.JSONField(blank=True, default=dict, verbose_name='Расхождения с БД')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Впервые увидели')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление записи')),
                ('last_imported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последний прогон импорта')),
                ('matched_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_rows', to='cargo.cargo', verbose_name='Сматченная партия')),
                ('matched_hawb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_rows', to='cargo.housewaybill', verbose_name='Сматченная HAWB')),
                ('promoted_hawb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from_rows', to='cargo.housewaybill', verbose_name='Создана HAWB')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='cargo.sheetsource')),
            ],
            options={
                'verbose_name': 'Строка из Sheets',
                'verbose_name_plural': 'Строки из Sheets',
                'ordering': ['source', 'source_row_index'],
            },
        ),
        migrations.CreateModel(
            name='HawbWorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TZ_AGREED', 'ТЗ согласовано'), ('GOV_CONTROL', 'Госконтроль'), ('VED_DOCS_COLLECTED', 'ВЭД собрал документы'), ('DOCS_PROVIDED', 'Документы предоставлены'), ('DOCS_REQUESTED', 'Запрос документов'), ('DOCS_RESPONSE', 'Ответ на запрос документов'), ('CALC_SENT', 'Отправлен расчёт ТП'), ('PAYMENT_DONE', 'Оплата счёта'), ('READY_TO_FILE', 'Готово к подаче'), ('FILED_FOR_CUSTOMS', 'Подано на ТО'), ('CUSTOMS_REQUEST', 'Запрос таможни'), ('VED_RESPONSE', 'Ответ ВЭДа по запросу таможни'), ('DECLARATION_ISSUED', '№ декларации на выпуск'), ('OTHER', 'Прочее')], db_index=True, max_length=32, verbose_name='Тип события')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='Когда произошло')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('raw_value', models.CharField(blank=True, max_length=255, verbose_name='Исходное значение')),
                ('source', models.CharField(choices=[('sheet', 'Из Google Sheets'), ('user', 'Вручную'), ('api', 'Внешний API')], default='sheet', max_length=10, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('hawb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_events', to='cargo.housewaybill')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_workflow_events', to=settings.AUTH_USER_MODEL)),
                ('source_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emitted_events', to='cargo.importedsheetrow')),
            ],
            options={
                'verbose_name': 'Событие workflow HAWB',
                'verbose_name_plural': 'События workflow HAWB',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='importedsheetrow',
            index=models.Index(fields=['match_status', 'source'], name='cargo_impor_match_s_48c5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='importedsheetrow',
            index=models.Index(fields=['hawb_number_norm'], name='cargo_impor_hawb_nu_6fb153_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='importedsheetrow',
            unique_together={('source', 'source_row_index')},
        ),
        migrations.AddIndex(
            model_name='hawbworkflowevent',
            index=models.Index(fields=['hawb', 'event_type', 'occurred_at'], name='cargo_hawbw_hawb_id_392430_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hawbworkflowevent',
            unique_together={('hawb', 'event_type', 'source_row')},
        ),
    ]
