# Generated by Django 5.2.14 on 2026-05-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0039_sheets_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedsheetrow',
            name='arrival_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата прибытия (из Sheets)'),
        ),
    ]
