# Generated by Django 5.2.14 on 2026-05-21 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0040_importedsheetrow_arrival_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltaInboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Envelope ID (Альта)')),
                ('msg_type', models.CharField(db_index=True, max_length=32, verbose_name='MessageType (ED.xxx)')),
                ('msg_kind', models.CharField(choices=[('registered', 'Регистрация ДТ'), ('released', 'Выпуск ДТ'), ('rejected', 'Отказ в выпуске'), ('examination', 'Досмотр / запрос'), ('hold', 'Требование / арест'), ('info', 'Информационное')], db_index=True, default='info', max_length=16, verbose_name='Semantic kind')),
                ('waybill_number_raw', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='WayBillNumber из XML')),
                ('declaration_number', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='№ ДТ из XML')),
                ('prepared_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки (PreparationDateTime)')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Записано в БД')),
                ('raw_xml', models.TextField(blank=True, verbose_name='Полный XML (для аудита)')),
                ('parsed_meta', models.JSONField(blank=True, default=dict, verbose_name='Распаршенные поля')),
                ('status_applied', models.BooleanField(db_index=True, default=False, verbose_name='Статус применён')),
                ('hawb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_messages', to='cargo.housewaybill', verbose_name='HAWB (сматчена)')),
            ],
            options={
                'verbose_name': 'Сообщение от таможни',
                'verbose_name_plural': 'Сообщения от таможни (входящие)',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['msg_kind', '-received_at'], name='cargo_altai_msg_kin_bc24ab_idx'), models.Index(fields=['hawb', '-received_at'], name='cargo_altai_hawb_id_457a6a_idx')],
            },
        ),
    ]
