# Generated by Django 5.2.14 on 2026-05-22 06:32

import re

from django.db import migrations, models


_ENV_RE = re.compile(rb'<(?:[a-z]+:)?EnvelopeID>([^<]+)', re.IGNORECASE)


def _backfill_envelope_ids(apps, schema_editor):
    """Парсит <roi:EnvelopeID> из content уже существующих записей.

    Для записей, у которых FK hawb обнулился (зомби с May 12) всё равно
    заполняем — пригодится для аудита и uniqueness.
    """
    AltaQueueItem = apps.get_model('cargo', 'AltaQueueItem')
    seen = set()
    for item in AltaQueueItem.objects.filter(envelope_id__isnull=True):
        content = item.content or b''
        if isinstance(content, memoryview):
            content = bytes(content)
        m = _ENV_RE.search(content)
        if not m:
            continue
        env_id = m.group(1).decode('ascii', errors='replace').strip()
        if not env_id or env_id in seen:
            continue
        seen.add(env_id)
        item.envelope_id = env_id
        item.save(update_fields=['envelope_id'])


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0041_altainboxmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='altaqueueitem',
            name='envelope_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Envelope ID (UUID)'),
        ),
        migrations.RunPython(_backfill_envelope_ids, _noop),
    ]
