# Generated by Django 5.2.14 on 2026-05-22 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0042_altaqueueitem_envelope_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltaOutboxObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Envelope ID (Альта)')),
                ('msg_type', models.CharField(db_index=True, max_length=32, verbose_name='MessageType')),
                ('prepared_at', models.DateTimeField(blank=True, null=True, verbose_name='PreparationDateTime')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Получено агентом')),
                ('common_waybill_number', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='CommonWayBillNumber (MAWB)')),
                ('waybill_number', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='WayBillNumber (HAWB)')),
                ('parsed_meta', models.JSONField(blank=True, default=dict, verbose_name='Распаршенные поля')),
            ],
            options={
                'verbose_name': 'Исходящая копия (Альта)',
                'verbose_name_plural': 'Исходящие копии (наблюдение)',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='altainboxmessage',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_messages', to='cargo.cargo', verbose_name='Партия (MAWB)'),
        ),
        migrations.AddIndex(
            model_name='altainboxmessage',
            index=models.Index(fields=['cargo', '-received_at'], name='cargo_altai_cargo_i_098f94_idx'),
        ),
        migrations.AddField(
            model_name='altaoutboxobservation',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox_observations', to='cargo.cargo', verbose_name='Партия (MAWB)'),
        ),
        migrations.AddField(
            model_name='altaoutboxobservation',
            name='hawb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox_observations', to='cargo.housewaybill', verbose_name='HAWB'),
        ),
        migrations.AddIndex(
            model_name='altaoutboxobservation',
            index=models.Index(fields=['msg_type', '-received_at'], name='cargo_altao_msg_typ_049915_idx'),
        ),
    ]
