# Generated by Django 5.2.14 on 2026-05-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0043_altaoutboxobservation_altainboxmessage_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='awb_number',
            field=models.CharField(db_index=True, help_text='AWB (123-12345678), CMR (050526-2), коносамент или любой другой ID партии', max_length=30, unique=True, verbose_name='Номер партии'),
        ),
    ]
