# Generated by Django 5.2.14 on 2026-05-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0044_alter_cargo_awb_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altainboxmessage',
            name='msg_kind',
            field=models.CharField(choices=[('registered', 'Регистрация ДТ'), ('released', 'Выпуск ДТ'), ('rejected', 'Отказ в выпуске'), ('withdrawn', 'Отзыв декларации'), ('examination', 'Досмотр / запрос'), ('hold', 'Требование / арест'), ('info', 'Информационное')], db_index=True, default='info', max_length=16, verbose_name='Semantic kind'),
        ),
    ]
