# Generated by Django 5.2.14 on 2026-05-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0045_alter_altainboxmessage_msg_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altainboxmessage',
            name='msg_kind',
            field=models.CharField(choices=[('registered', 'Регистрация ДТ'), ('released', 'Выпуск ДТ'), ('rejected', 'Отказ в выпуске'), ('withdrawn', 'Отзыв декларации'), ('examination', 'Досмотр / запрос'), ('hold', 'Требование / арест'), ('svh_placed', 'Размещение на СВХ (ДО1)'), ('info', 'Информационное')], db_index=True, default='info', max_length=16, verbose_name='Semantic kind'),
        ),
    ]
