# Generated by Django 5.2.14 on 2026-05-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0046_alta_svh_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='svh_do1_reg_number',
            field=models.CharField(blank=True, help_text='10001020/220526/5005840 — из CMN.13029 (опись СВХ)', max_length=64, verbose_name='Рег. номер ДО1'),
        ),
    ]
