# Generated by Django 5.2.14 on 2026-05-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0047_cargo_svh_do1_reg_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altainboxmessage',
            name='msg_kind',
            field=models.CharField(choices=[('registered', 'Регистрация ДТ'), ('released', 'Выпуск ДТ'), ('rejected', 'Отказ в выпуске'), ('withdrawn', 'Отзыв декларации'), ('examination', 'Досмотр / запрос'), ('hold', 'Требование / арест'), ('svh_placed', 'Представление СВХ (CMN.13029)'), ('svh_do1_registered', 'Регистрация ДО1 (CMN.13010)'), ('info', 'Информационное')], db_index=True, default='info', max_length=24, verbose_name='Semantic kind'),
        ),
    ]
