# Generated by Django 5.2.14 on 2026-05-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0048_alta_svh_do1_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedsheetrow',
            name='match_status',
            field=models.CharField(choices=[('unmatched', 'Не обработано'), ('matched', 'Совпадает с HAWB'), ('orphan', 'Нет соответствия в БД'), ('conflict', 'Несколько кандидатов'), ('ambiguous', 'Нет ключа для матчинга'), ('promoted', 'Промоутнуто в HAWB'), ('duplicate', 'Дубль в Sheets (другая строка победила)'), ('ignored', 'Исключено вручную')], db_index=True, default='unmatched', max_length=20, verbose_name='Статус матчинга'),
        ),
    ]
