# Generated by Django 5.2.14 on 2026-05-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0049_sheets_duplicate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='housewaybill',
            name='filed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подачи'),
        ),
    ]
