# Generated by Django 5.2.14 on 2026-05-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0050_hawb_filed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='svh_do2_reg_number',
            field=models.CharField(blank=True, help_text='10001020/240526/5049065 — из CMN.13014 (выпуск со СВХ)', max_length=64, verbose_name='Рег. номер ДО2'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='svh_do2_send_at',
            field=models.DateTimeField(blank=True, help_text='SendDate+SendTime из CMN.13014 — момент выпуска со СВХ', null=True, verbose_name='Дата ДО2'),
        ),
    ]
