# Generated by Django 5.2.14 on 2026-05-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0051_cargo_svh_do2_reg_number_cargo_svh_do2_send_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='svh_do2_reg_number',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='svh_do2_send_at',
        ),
        migrations.AddField(
            model_name='housewaybill',
            name='svh_do2_send_at',
            field=models.DateTimeField(blank=True, help_text='SendDate+SendTime из CMN.13014 (выпуск этой накладной со СВХ). Привязка через TransportDoc или ProduceDocuments (рег.номер ДТ).', null=True, verbose_name='Дата ДО2'),
        ),
    ]
