# Generated by Django 5.2.14 on 2026-05-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0055_move_svh_do1_sent_at_to_hawb'),
    ]

    operations = [
        migrations.AddField(
            model_name='housewaybill',
            name='goods_count',
            field=models.PositiveIntegerField(blank=True, help_text='Число товарных позиций в ДТ. CMN.11023: общее по декларации (одинаково у всех HAWB одной ДТ). CMN.11349: per-HAWB.', null=True, verbose_name='Количество позиций'),
        ),
    ]
