# Generated by Django 5.2.14 on 2026-05-28 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0056_housewaybill_goods_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='HawbCustomsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Envelope ID')),
                ('initial_envelope_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='InitialEnvelopeID (наш CMN)')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Получено')),
                ('prepared_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки (envelope)')),
                ('request_dt_msk', models.DateTimeField(blank=True, db_index=True, help_text='RequestDate+RequestTime, переведённое в МСК. Используется для группировки в Sheets.', null=True, verbose_name='Время запроса (МСК)')),
                ('date_limit', models.DateField(blank=True, null=True, verbose_name='Срок ответа')),
                ('request_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Позиция товара в декларации')),
                ('requestor_name', models.CharField(blank=True, max_length=200, verbose_name='Имя инспектора')),
                ('customs_code', models.CharField(blank=True, max_length=20, verbose_name='Код таможни')),
                ('office_name', models.CharField(blank=True, max_length=200, verbose_name='Таможенный пост')),
                ('request_text', models.TextField(blank=True, verbose_name='Текст запроса')),
                ('raw_xml', models.TextField(blank=True, verbose_name='Полный XML')),
                ('parsed_meta', models.JSONField(blank=True, default=dict, verbose_name='Распаршенные поля')),
                ('hawb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customs_requests', to='cargo.housewaybill', verbose_name='HAWB (привязка по Position)')),
            ],
            options={
                'verbose_name': 'Запрос таможни (MY.11003)',
                'verbose_name_plural': 'Запросы таможни (входящие MY.11003)',
                'ordering': ['-request_dt_msk', '-received_at'],
                'indexes': [models.Index(fields=['hawb', '-request_dt_msk'], name='cargo_hawbc_hawb_id_725bf8_idx'), models.Index(fields=['initial_envelope_id'], name='cargo_hawbc_initial_8dc258_idx')],
            },
        ),
    ]
