# Generated by Django 5.2.14 on 2026-05-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0057_hawbcustomsrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hawbcustomsrequest',
            options={'ordering': ['-request_dt_msk', '-received_at'], 'verbose_name': 'Запрос таможни (ED.11003)', 'verbose_name_plural': 'Запросы таможни (входящие ED.11003)'},
        ),
        migrations.AddField(
            model_name='hawbcustomsrequest',
            name='request_position_id',
            field=models.CharField(blank=True, db_index=True, help_text='Один ED.11003 envelope содержит N <RequestedDoc>. request_position_id уникально идентифицирует запрос в рамках envelope.', max_length=64, verbose_name='RequestPositionID (UUID запроса)'),
        ),
        migrations.AlterField(
            model_name='hawbcustomsrequest',
            name='envelope_id',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Envelope ID (ED.11003)'),
        ),
        migrations.AddConstraint(
            model_name='hawbcustomsrequest',
            constraint=models.UniqueConstraint(fields=('envelope_id', 'request_position_id'), name='hawbcustomsrequest_env_pos_uniq'),
        ),
    ]
