# Generated by Django 5.2.14 on 2026-05-28 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0058_alter_hawbcustomsrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HawbDeclarationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_number', models.CharField(db_index=True, max_length=64, verbose_name='Рег. номер ДТ')),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='1, 2, 3... в порядке появления. Первая подача = 1.', verbose_name='Порядковый номер попытки')),
                ('status', models.CharField(choices=[('FILED', 'Подано'), ('RELEASED', 'Выпуск'), ('REJECTED', 'Отказ'), ('WITHDRAWN', 'Отозвано')], db_index=True, default='FILED', max_length=16, verbose_name='Статус')),
                ('filed_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата подачи')),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('rejected_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отказа')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('hawb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaration_attempts', to='cargo.housewaybill', verbose_name='HAWB')),
            ],
            options={
                'verbose_name': 'Попытка подачи ДТ',
                'verbose_name_plural': 'Попытки подачи ДТ',
                'ordering': ['hawb', 'attempt_number'],
                'indexes': [models.Index(fields=['hawb', 'attempt_number'], name='cargo_hawbd_hawb_id_4491c3_idx')],
                'constraints': [models.UniqueConstraint(fields=('hawb', 'declaration_number'), name='hawbdeclattempt_hawb_decl_uniq')],
            },
        ),
    ]
