# Generated by Django 5.2.14 on 2026-05-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0059_hawbdeclarationattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='housewaybill',
            name='declaration_form',
            field=models.CharField(blank=True, choices=[('', '—'), ('ПТДЭГ', 'ПТДЭГ — предварительная ДТЭГ (CMN.11335)'), ('ДТЭГ', 'ДТЭГ — декларация на экспресс-грузы (CMN.11349)'), ('ДТ', 'ДТ — классическая декларация (CMN.11024)')], help_text='ПТДЭГ → ДТЭГ → ДТ. Перезаписывается при появлении нового outbox-сообщения этого типа (естественная воронка).', max_length=8, verbose_name='Тип декларации'),
        ),
        migrations.AlterField(
            model_name='sheetsource',
            name='kind',
            field=models.CharField(choices=[('general', 'Таблица "Общее"'), ('crm', 'Таблица CRM'), ('export', 'Экспортная статистика')], db_index=True, max_length=20, verbose_name='Тип источника'),
        ),
    ]
