# Generated by Django 5.2.14 on 2026-05-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0060_export_declaration_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='housewaybill',
            name='ed_status',
            field=models.CharField(blank=True, help_text='Реконструированный статус из ED-обмена с таможней (аналог "ЭД-статус" в Альте). Обновляется при каждом входящем CMN-сообщении. Фраза + опц. флаги через "; ".', max_length=64, verbose_name='Статус ЭД'),
        ),
    ]
