# Generated by Django 5.2.14 on 2026-05-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0061_housewaybill_ed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='housewaybill',
            name='declarant_name',
            field=models.CharField(blank=True, help_text='ФИО декларанта из <SignatoryPerson><SigningDetails> в исходящей CMN.11335/11349/11024 (только для EXPORT).', max_length=200, verbose_name='Декларант (ФИО)'),
        ),
    ]
