# Generated by Django 5.2.14 on 2026-06-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0064_crmhawbindex_last_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdekStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(db_index=True, max_length=32, verbose_name='Код статуса')),
                ('status_name', models.CharField(blank=True, max_length=128, verbose_name='Статус')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='Когда произошло')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='Город')),
                ('cdek_uuid', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='CDEK UUID заказа')),
                ('cdek_number', models.CharField(blank=True, max_length=32, verbose_name='Номер заказа СДЭК')),
                ('source', models.CharField(choices=[('webhook', 'Вебхук СДЭК'), ('poll', 'Опрос API'), ('manual', 'Вручную (кнопка)')], default='webhook', max_length=10, verbose_name='Источник')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Сырой статус')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
            ],
            options={
                'verbose_name': 'Статус доставки СДЭК',
                'verbose_name_plural': 'Статусы доставки СДЭК',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='housewaybill',
            name='cdek_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Номер заказа СДЭК'),
        ),
        migrations.AddField(
            model_name='housewaybill',
            name='cdek_status_code',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Код статуса СДЭК'),
        ),
        migrations.AddField(
            model_name='housewaybill',
            name='cdek_status_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата статуса СДЭК'),
        ),
        migrations.AddField(
            model_name='housewaybill',
            name='cdek_status_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Статус СДЭК'),
        ),
        migrations.AddField(
            model_name='housewaybill',
            name='cdek_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Синхронизация СДЭК'),
        ),
        migrations.AddField(
            model_name='housewaybill',
            name='cdek_uuid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='CDEK UUID заказа'),
        ),
        migrations.AddField(
            model_name='cdekstatusevent',
            name='hawb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdek_events', to='cargo.housewaybill'),
        ),
        migrations.AddIndex(
            model_name='cdekstatusevent',
            index=models.Index(fields=['hawb', '-occurred_at'], name='cargo_cdeks_hawb_id_43a681_idx'),
        ),
        migrations.AddConstraint(
            model_name='cdekstatusevent',
            constraint=models.UniqueConstraint(fields=('hawb', 'status_code', 'occurred_at'), name='cdekstatusevent_idem_uniq'),
        ),
    ]
