# Generated by Django 5.2.14 on 2026-06-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0067_deklarant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='crmhawbindex',
            new_name='cargo_crmha_tab_nam_0d298c_idx',
            old_name='cargo_crmha_tab_nam_idx',
        ),
        migrations.RenameIndex(
            model_name='crmhawbindex',
            new_name='cargo_crmha_hawb_nu_ce56a7_idx',
            old_name='cargo_crmha_hawb_nu_idx',
        ),
        migrations.AlterField(
            model_name='crmhawbindex',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='housewaybill',
            name='customs_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('BROKER_CHECK', 'Проверка брокером'), ('READY_TO_FILE', 'Готов к подаче'), ('FILED', 'Подан на таможенное оформление'), ('EXAMINATION', 'Досмотр'), ('HOLD', 'Удержан таможней'), ('RELEASED', 'Выпущен'), ('REJECTED', 'Отказ в выпуске'), ('WITHDRAWN', 'Отозвана')], default='', max_length=20, verbose_name='Таможенный статус'),
        ),
    ]
