# Generated by Django 5.2.14 on 2026-06-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0068_add_customs_status_withdrawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='svh_source',
            field=models.CharField(blank=True, choices=[('', '—'), ('alta', 'Альта-СВХ (Внуково)'), ('moscow_cargo', 'Москва-Карго (Шереметьево)'), ('shercargo', 'Шереметьево-Карго (shercargo.ru)'), ('deklarant', 'Декларант Плюс (Таможенный портал ДВ)'), ('manual', 'Вручную')], db_index=True, default='', max_length=20, verbose_name='Источник СВХ-данных'),
        ),
    ]
