# Generated by Django 5.2.14 on 2026-08-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0070_altaoutboxwaybill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseReestrNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hawb_number', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Накладная')),
                ('to_email', models.CharField(blank=True, max_length=255, verbose_name='Кому')),
                ('status', models.CharField(choices=[('SENT', 'Отправлено'), ('FAILED', 'Ошибка отправки'), ('SKIPPED', 'Отложено (нет подачи)')], db_index=True, default='SENT', max_length=16, verbose_name='Статус')),
                ('msg_type', models.CharField(blank=True, max_length=32, verbose_name='Тип сообщения подачи')),
                ('registration_number', models.CharField(blank=True, max_length=64, verbose_name='Рег. номер ДТ')),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попыток')),
                ('error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Рассылка реестра при выпуске',
                'verbose_name_plural': 'Рассылки реестров при выпуске',
                'ordering': ['-created_at'],
            },
        ),
    ]
