# Generated by Django 5.2.14 on 2026-08-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0071_releasereestrnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='transit_doc',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Транзитный документ (СМР)'),
        ),
    ]
