# Generated by Django 5.2.14 on 2026-08-10 09:17

import cargo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0073_reestr_status_excluded'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingDTDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_number', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Рег.№ ДТ')),
                ('pdf', models.FileField(blank=True, max_length=255, upload_to=cargo.models.incoming_dt_upload_to, verbose_name='PDF-бланк ДТ')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='Размер, байт')),
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='SHA-256')),
                ('status', models.CharField(choices=[('pending', 'В очереди на рассылку'), ('sent', 'Разослан'), ('failed', 'Ошибка отправки'), ('purged', 'Файл удалён / дубль')], db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('to_email', models.CharField(blank=True, max_length=255, verbose_name='Кому разослан')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попыток')),
                ('error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Получен')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Разослан в')),
                ('purged_at', models.DateTimeField(blank=True, null=True, verbose_name='Файл удалён')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('hawb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_dt_docs', to='cargo.housewaybill', verbose_name='Накладная')),
            ],
            options={
                'verbose_name': 'Входящий PDF ДТ',
                'verbose_name_plural': 'Входящие PDF ДТ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='cargo_incom_status_68ad42_idx')],
            },
        ),
    ]
